name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install license-header-checker
      run: curl -s https://raw.githubusercontent.com/lluissm/license-header-checker/master/install.sh | bash
    - name: Run license check
      run: ./bin/license-header-checker -a -r -i . cs js ts && [[ -z `git status -s` ]]
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
